// Code generated by ezgen. DO NOT EDIT.
// Code generated by ezgen. DO NOT EDIT.
// Code generated by ezgen. DO NOT EDIT.

package dao

import (
	"sync"

	"{{.ModelPackage}}/internal/constants"

	"go.uber.org/mock/gomock"
	"gorm.io/gorm"
)

var (
	initOnce sync.Once
	initMockOnce sync.Once

	{{range $index, $modelName := .ModelNameList}}
	{{$modelName}} i{{$modelName}}Dao
	{{- end}}
)

// Init initializes all Dao structures
func Init(mysql *gorm.DB) {
	initOnce.Do(func() {
		{{range $index, $modelName := .ModelNameList}}
		{{$modelName}} = &{{index $.DaoNameList $index}}{db: mysql}
		{{- end}}
	})
}

type getConfig struct {
	Cached constants.CacheMode
	WithDeleted bool
}

type GetOption func(*getConfig)

func WithCached(cached constants.CacheMode) GetOption {
	return func(cfg *getConfig) {
		cfg.Cached = cached
	}
}

func WithDeleted(withDeleted bool) GetOption {
	return func(cfg *getConfig) {
		cfg.WithDeleted = withDeleted
	}
}
