// Code generated by go-exp. DO NOT EDIT.

package dao

import (
	"sync"

	"gorm.io/gorm"
)

var (
	initOnce sync.Once

	{{range $index, $modelName := .ModelNameList}}
	{{$modelName}} *{{index $.DaoNameList $index}}
	{{- end}}
)

// Init initializes all DAO structures
func Init(mysql *gorm.DB) {
	initOnce.Do(func() {
		{{range $index, $modelName := .ModelNameList}}
		{{$modelName}} = &{{index $.DaoNameList $index}}{db: mysql}
		{{- end}}
	})
}
